using System;
using System.Collections.Generic;
using System.Text;

namespace PayFabric.Net.Models
{
    public class PayFabricResponse
    {
        /// <summary>
        /// PayFabric transaction key. This is generated upon creation of the transaction in the PayFabric server.
        /// </summary>
        public string TrxKey { get; set; }

        /// <summary>
        /// Authorization code. Generated by the Payment Gateway.
        /// </summary>
        public string AuthCode { get; set; }

        /// <summary>
        /// Status of transaction. Generated by the Payment Gateway. Possible values are Approved, Denied, Declined, Failure, AVSFailure, and More Info.
        /// </summary>
        public string Status { get; set; }

        /// <summary>
        /// Result code of the transaction. Generated by the Payment Gateway.
        /// </summary>
        public string ResultCode { get; set; }

        /// <summary>
        /// Result message of the transaction. Generated by the Payment Gateway.
        /// </summary>
        public string Message { get; set; }

        /// <summary>
        /// Unique identifier for the transaction. Generated by the Payment Gateway.
        /// </summary>
        public string OriginationID { get; set; }

        /// <summary>
        /// Date of transaction. It's format should like "3/23/2015 11:16:19 PM".
        /// </summary>
        public DateTime? TrxDate { get; set; }

        /// <summary>
        /// A tag value which is generated by FirstData, which must be included when submitting a transaction to FirstData. This is only valid if FirstData GGe4 is the Payment Gateway.
        /// </summary>
        public string RespTrxTag { get; set; }

        /// <summary>
        /// Verification status code of CVC code. Generated by the Payment Gateway.
        /// </summary>
        public string CVV2Response { get; set; }

        /// <summary>
        /// Verification status code of zip code. Generated by the Payment Gateway.
        /// </summary>
        public string AVSZipResponse { get; set; }

        /// <summary>
        /// Verification status code of billing address. Generated by the Payment Gateway.
        /// </summary>
        public string AVSAddressResponse { get; set; }

        /// <summary>
        /// Flag indicating that address verification has been ignored because the address is an international address. Generated by the Payment Gateway.
        /// </summary>
        public string IAVSAddressResponse { get; set; }
        public string PayFabricErrorCode { get; set; }
        public string TAXml { get; set; }
        public string TerminalID { get; set; }
        public string TerminalResultCode { get; set; }
    }
}
