using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Text;

namespace PayFabric.Net.Models
{
    public partial class SimpleTransaction
    {
        /// <summary>
        /// PayFabric transaction key. This is generated by PayFabric upon creation of the transaction.
        /// </summary>
        [MaxLength(64)]
        public string Key { get; set; }

        /// <summary>
        /// Unique identifier of the transaction. Generated by the Payment Gateway.
        /// </summary>
        public string OriginationID { get; set; }

        /// <summary>
        /// Status message indicating the status of the transaction. Possible values are Approved, Denied, Declined, Failure, AVSFailure, More Info.
        /// </summary>
        public string Status { get; set; }

        /// <summary>
        /// Transaction date. It's format should like "3/23/2015 11:16:19 PM".
        /// </summary>
        public string TrxDate { get; set; }

        /// <summary>
        /// Transaction type. The possible values are Sale,Book,Ship,Void,Credit,Force.
        /// </summary>
        public string Type { get; set; }
    }
}
