using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Text;

namespace PayFabric.Net.Models
{
    public class TransactionResponse
    {
        /// <summary>
        /// PayFabric transaction key. This is generated upon creation of the transaction in the PayFabric server.
        /// </summary>
        [JsonProperty("TrxKey")]
        public string TransactionKey { get; set; }

        /// <summary>
        /// Authorization code. Generated by the Payment Gateway.
        /// </summary>
        [JsonProperty("AuthCode")]
        public string AuthorizationCode { get; set; }

        /// <summary>
        /// Status of transaction. Generated by the Payment Gateway. Possible values are Approved, Denied, Declined, Failure, AVSFailure, and More Info.
        /// </summary>
        public string Status { get; set; }

        /// <summary>
        /// Result code of the transaction. Generated by the Payment Gateway.
        /// </summary>
        public string ResultCode { get; set; }

        /// <summary>
        /// Result message of the transaction. Generated by the Payment Gateway.
        /// </summary>
        public string Message { get; set; }

        /// <summary>
        /// Unique identifier for the transaction. Generated by the Payment Gateway.
        /// </summary>
        public string OriginationID { get; set; }

        /// <summary>
        /// Date of transaction. It's format should like "3/23/2015 11:16:19 PM".
        /// </summary>
        [JsonProperty("TrxDate")]
        public DateTime? TransactionDate { get; set; }

        /// <summary>
        /// A tag value which is generated by FirstData, which must be included when submitting a transaction to FirstData. This is only valid if FirstData GGe4 is the Payment Gateway.
        /// </summary>
        public string RespTrxTag { get; set; }

        /// <summary>
        /// Verification status code of CVC code. Generated by the Payment Gateway.
        /// </summary>
        public string CVV2Response { get; set; }

        /// <summary>
        /// Verification status code of zip code. Generated by the Payment Gateway.
        /// </summary>
        public string AVSZipResponse { get; set; }

        /// <summary>
        /// Verification status code of billing address. Generated by the Payment Gateway.
        /// </summary>
        public string AVSAddressResponse { get; set; }

        /// <summary>
        /// Flag indicating that address verification has been ignored because the address is an international address. Generated by the Payment Gateway.
        /// </summary>
        public string IAVSAddressResponse { get; set; }

        /// <summary>
        /// Undocumented - guess, payfabric error code? 
        /// </summary>
        public string PayFabricErrorCode { get; set; }

        /// <summary>
        /// Undocumented - guess, surcharge
        /// </summary>
        public decimal? SurchargeAmount { get; set; } 

        /// <summary>
        /// Undocumented - guess, surcharge percentage
        /// </summary>
        public decimal? SurchargePercentage { get; set; }

        /// <summary>
        /// Undocumented - guess, original transaction amount
        /// </summary>
        [JsonProperty("OrigTrxAmount")]
        public decimal? OriginalTransactionAmount { get; set; }

        /// <summary>
        /// Undocumented - guess, original transaction amount plus surcharge
        /// </summary>
        public decimal? FinalAmount { get; set; } 

        /// <summary>
        /// Undocumented - guess, Card Type
        /// </summary>
        public string CardType { get; set; } 

        /// <summary>
        /// Undocumented - guess, xml transaction returned from payment gateway
        /// </summary>
        [JsonProperty("TAXml")]
        public string TransactionXml { get; set; }

        /// <summary>
        /// Undocumented 
        /// </summary>
        [JsonProperty("TrxAmount")]
        public decimal? TransactionAmount { get; set; }

        /// <summary>
        /// Undocumented
        /// </summary>
        public string TerminalID { get; set; }

        /// <summary>
        /// Undocumented
        /// </summary>
        public string TerminalResultCode { get; set; }
    }
}
